name: Build and Test
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build main program
        run: gcc main.c lib.c -o binaryoutput

      - name: Build test program
        run: gcc test.c lib.c -o testbinary

      - name: Run tests
        run: ./testbinary

